### ISSUE TITLE
Reverse dependency check failure with raster 3.6.0

### ISSUE THREAD

**Issue by rsbivand** [waternumbers/dynatopGIS#30] opened 2022-09-05 08:03 UTC
Careful checking of your package as **raster** replaces **rgdal** and **rgeos** is advised. With raster development version 3.6.0 (and PROJ 9.1.0, GDAL 3.5.2), I get:
[00check.log](https://github.com/waternumbers/dynatopGIS/files/9487876/00check.log)

**Comment by waternumbers** [comment] 2022-09-06 16:51
Thanks, changed master branch so dependency on `rgoes` and `rgdal` is via the `raster` package and can be removed when `raster` doesn't need `rgdal` to write tif files.

 Would test with `raster` 3.6.0 but I'm having issues getting it to work - [see here](https://github.com/rspatial/raster/issues/284)

**Comment by waternumbers** [comment] 2022-09-06 21:46
Working with `raster` 3.6.0. The error is caused by the different behaviour or raster 3.2.59 and 3.6.0 when writing and reading NA values.

With the current versions of raster (3.2.58) and terra (1.6.7) the behaviour look like

```
r <-  raster::raster(ncols=3, nrows=3)
r[] <- NA
raster::writeRaster(r,"na.tif")

is.nan(raster::raster("na.tif"))
## class      : RasterLayer 
## dimensions : 3, 3, 9  (nrow, ncol, ncell)
## resolution : 120, 60  (x, y)
## extent     : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
## crs        : +proj=longlat +datum=WGS84 +no_defs 
## source     : memory
## names      : layer 
## values     : 0, 0  (min, max)

is.nan(terra::rast("na.tif"))
## class       : SpatRaster 
## dimensions  : 3, 3, 1  (nrow, ncol, nlyr)
## resolution  : 120, 60  (x, y)
## extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
## coord. ref. : lon/lat WGS 84 (EPSG:4326) 
## source      : memory 
## name        :   na 
## min value   : TRUE 
## max value   : TRUE 
```
The logical values for testing for NaN are different. `raster` v3.6.0 gives

```
is.nan(raster::raster("na.tif"))
## class      : RasterLayer 
## dimensions : 3, 3, 9  (nrow, ncol, ncell)
## resolution : 120, 60  (x, y)
## extent     : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
## crs        : +proj=longlat +datum=WGS84 +no_defs 
## source     : memory
## names      : layer 
## values     : 1, 1  (min, max)
```
That is the same result as `terra` and inconsistent with the previous raster version. This has impacts - for example `zonal` ignores `NA` but not `NaN`. 
@rsbivand is this an intentional change? If so could it be documented in NEWS?

**Comment by rsbivand** [comment] 2022-09-07 07:43
I just do reverse dependency checks for **rgdal** etc., **raster** isn't maintained by me. Did https://github.com/rspatial/raster/issues/284 help? The underlying reason is that **terra** is starting to be used by **raster** for everything **rgdal** and **rgeos** used to do, and since they are retiring shortly, **raster** is moving closer to **terra** in many ways. Shifting your package to only use **terra** will make the transition simpler. You also need to replace **rgeos** and **rgdal** ASAP, as you know from https://r-spatial.org/r/2022/04/12/evolution.html

**Comment by waternumbers** [comment] 2022-09-07 08:59
OK, will report the change in behaviour to the *raster* maintainers. Current master branch works with the development version of *raster* 3.6.0 with no *rgdal*/*rgeos*. This will go to CRAN when I have an answer whether the changes in behaviour are expected. The final dependency on *rgdal* (via *raster* to allow writing of tif files) can then be removed when *raster* 3.6.0 is released.

The next version of *dynatopGIS* (v0.3 branch), which might be out by the end of the year, uses *terra* but includes other breaking changes.

**Comment by waternumbers** [comment] 2022-12-06 09:44
Switch to `terra` package in v0.2.4 which removes this issue so closing.

**Closed as completed by waternumbers** 2022-12-06 09:44 UTC

**Comment by rsbivand** [comment] 2022-12-06 13:59
Repo HEAD check cleanly on the system which failed before, with current raster/terra:

[00check.log](https://github.com/waternumbers/dynatopGIS/files/10167055/00check.log)
